### ISSUE TITLE
Bug: Reference to model Openshift but Openshift does not exist in swagger.yml

### ISSUE THREAD

**Issue by mcanoy** [rht-labs/api-design#15]
Check out https://github.com/rht-labs/api-design/blob/master/swagger.yaml#L1044

The definition OpenshiftCluster is referencing openshift but there is no Openshift defined.

OpenshiftCluster:
    ....
      **openshift:
        $ref: '#/definitions/Openshift'**
      openshift_resources_to_create:
        $ref: '#/definitions/OpenshiftResources'
      openshift_host_env:
        type: string
      image_registry:
        $ref: "#/definitions/ImageRegistry

**Comment by sherl0cks** [comment]
Yeap, hit this myself. Will fix shortly
